### ISSUE TITLE
HTML muy completo y con demasiados contenedores

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-annabranco#1]
No todo tiene que estar dentro de un section, ya que `<header>` ya dice que es una sección. 
Podríamos decir que los `<section>` tienen más sentido dentro del main...

Serías capaz de reajustarlo para este html?

```html
  <header class="head">
    <div class="logo">
      <img src="images/logo_adalab_155x61.png">
    </div>
    <nav class="links-box">
      <ul class="menu">
        <li class="menu-item"><a href="">Blog</a></li>
        <li class="menu-item"><a href="">Contacto</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="main-box">
      <h1>Creando Diversidad Digital</h>
    </section>
  </main>
```

![Al turrón](https://media1.tenor.com/images/01841e3c660004c3c70554643788a6b1/tenor.gif?itemid=4901091)

**Comment by annabranco** [comment]
Ok. Hecho. Ya está en un commit. ^^
Cuando termine todos los issues hago un solo push.

**Comment by annabranco** [comment]
He revisado todo el código, excluyendo todos los DIVs realmente no necesarios (al final borré **todos** 🤣).
He limpiado también el CSS. Visualizando en el Inspector, fui probando a desactivar uno a uno todos los estilos que había definido, y mirando si cambiaban alguna cosa en la página (en sus dos _viewports_). 
❓**Es una buena práctica, o puede generar algún problema??**
Al final que borrado muchísimos códigos de estilo que aparentemente no producían ningún resultado. 

Los dos códigos _html_ y _css_ quedaron muchísimo más limpios la verdad.
Todos estos cambios fueron realizados en el commit 8b738c4, que generó la versión final.
