### ISSUE TITLE
Etiquetas sin contenido, y por tanto, sin cierre

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-annabranco#2]
Hay una serie de etiquetas que no admiten contenido, como:

- `<br>`
- `<hr>` 
- `<input>`
- `<img>`

Estas etiquetas no se cierran. En tu código hay una de ellas que está cerrada ;)

**Comment by annabranco** [comment]
</img>?!?!? De dónde he sacado esto???? LOL :~D

Done!
