### ISSUE TITLE
Deberíamos usar selectores de clase y nunca de etiqueta

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-annabranco#3]
Salvo el body, que a esta etiqueta se le perdona todo

**Comment by annabranco** [comment]
Te refieres, por ejemplo, a 
```
  .logo img {
    width: 155px;
    margin: 10px;
  }
```
???

Creía que no estaba mal, una vez que es un selector de un elemento que está dentro de una clase.

✅ ¡Corregido!
