### ISSUE TITLE
La cabecera debería estar fija

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-annabranco#4]
Qué, nos animamos a darle la puntilla al ejercicio?

![Adelante](https://media1.tenor.com/images/dd3f3cc592630400fc604b609feee540/tenor.gif?itemid=5470798)

**Comment by annabranco** [comment]
@oneeyedman >>  Pero creo que ya estaba, no?

`  .head {
    background: white;
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: stretch;
    **position: fixed;**
    top: 0;
    left: 0;
  }`

**Comment by annabranco** [comment]
Ahhh, ya lo entiendo.
Lo había cambiado, pero no había subido la versión ajustada antes de que tu corrección.

Solucionado en el commit "Algunos ajustes que habia hecho previamente pero que no habian sido '…"  ( 522556b ).
✅Done!
